# Generated by Django 4.2.15 on 2024-08-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=120)),
                ('titulo', models.CharField(max_length=100)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Livro_emprestado',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.cliente')),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.biblioteca')),
            ],
        ),
    ]
