# Generated by Django 4.2.15 on 2024-08-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='nome',
            field=models.CharField(default='', max_length=120),
        ),
    ]
