# Generated by Django 4.2.15 on 2024-08-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_admin_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='senha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='livro_emprestado',
            name='data_emprestimo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
