# Generated by Django 5.1 on 2024-08-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0003_admin_senha_cliente_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='cpf',
            field=models.CharField(default='', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
