# Generated by Django 5.1 on 2024-08-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0004_admin_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='senha',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='', max_length=128),
        ),
    ]
