# Generated by Django 5.1 on 2024-08-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0005_alter_admin_senha_alter_cliente_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='cnpj',
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
    ]
