# Generated by Django 5.1 on 2024-08-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0006_remove_admin_cnpj_remove_cliente_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='cad_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca_app.admin'),
        ),
    ]
