# Generated by Django 5.1 on 2024-08-29 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0007_livro_cad_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='estoque',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
