# Generated by Django 5.1 on 2024-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0009_livro_capa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('Ficção', 'Ficção'), ('Não Ficção', 'Não Ficção'), ('Biografia', 'Biografia'), ('Fantasia', 'Fantasia')], default='Ficção', max_length=20),
        ),
    ]
