# Generated by Django 5.1 on 2024-08-31 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0012_alter_carrinho_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.cliente'),
        ),
    ]
