# Generated by Django 5.1.1 on 2024-09-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0013_alter_carrinho_cliente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrinho',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('Ficção Científica', 'Ficção Científica'), ('Não Ficção', 'Não Ficção'), ('Biografia', 'Biografia'), ('Fantasia', 'Fantasia')], default='Ficção Científica', max_length=20),
        ),
    ]
