# Generated by Django 5.1.1 on 2024-09-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0015_alter_livro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('Ficção Científica', 'Ficção Científica'), ('Não Ficção', 'Não Ficção'), ('Biografia', 'Biografia'), ('Fantasia', 'Fantasia'), ('Horror', 'Horror'), ('Infantil', 'Infantil'), ('Acadêmico', 'Acadêmico'), ('Autoajuda', 'Autoajuda'), ('HQs e Mangás', 'HQs e Mangás'), ('Filosofia', 'Filosofia'), ('Romance', 'Romance'), ('Arte', 'Arte'), ('Tecnologia', 'Tecnologia'), ('Mistério', 'Mistério')], default='Ficção Científica', max_length=40),
        ),
    ]
