# Generated by Django 5.1.1 on 2024-09-12 19:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0016_alter_livro_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='livro',
        ),
        migrations.AddField(
            model_name='livro_emprestado',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 19, 29, 58, 651349, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Livro_Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.carrinho')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.livro')),
            ],
            options={
                'unique_together': {('carrinho', 'livro')},
            },
        ),
    ]
