# Generated by Django 5.1.1 on 2024-09-12 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0017_remove_carrinho_livro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro_emprestado',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 19, 51, 7, 18168, tzinfo=datetime.timezone.utc)),
        ),
    ]
