# Generated by Django 5.1.1 on 2024-09-19 12:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0018_alter_livro_emprestado_data_devolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='livro_emprestado',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 12, 16, 44, 985238, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.genero'),
        ),
    ]
