# Generated by Django 5.1.1 on 2024-09-20 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0019_genero_alter_livro_emprestado_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro_emprestado',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 13, 44, 44, 749162, tzinfo=datetime.timezone.utc)),
        ),
    ]
