# Generated by Django 5.1.1 on 2024-09-23 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0020_alter_livro_emprestado_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro_emprestado',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 18, 50, 23, 396000, tzinfo=datetime.timezone.utc)),
        ),
    ]
