# Generated by Django 5.1.1 on 2024-09-23 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0023_alter_livro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.genero'),
            preserve_default=False,
        ),
    ]
