# Generated by Django 5.1 on 2024-09-24 15:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0026_alter_cliente_options_alter_cliente_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='senha',
            new_name='senha_hash',
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.cliente'),
        ),
        migrations.AlterField(
            model_name='livro_emprestado',
            name='data_devolucao',
            field=models.DateField(default=datetime.date(2024, 10, 24)),
        ),
    ]
