# Generated by Django 5.1.1 on 2024-09-25 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0027_rename_senha_cliente_senha_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro_emprestado',
            name='data_devolucao',
            field=models.DateField(default=datetime.date(2024, 10, 25)),
        ),
    ]
